export const ENV_VARS = {
    MAPBOX_API_KEY: process.env.NEXT_PUBLIC_MAPBOX_API_KEY,
    EMAILJS_SERVICE: process.env.NEXT_PUBLIC_EMAILJS_SERVICE,
    EMAILJS_SUBSCRIBE_TEMPLATE: process.env.NEXT_PUBLIC_EMAILJS_SUBSCRIBE_TEMPLATE,
    EMAILJS_CONTACT_TEMPLATE: process.env.NEXT_PUBLIC_EMAILJS_CONTACT_TEMPLATE,
    EMAILJS_PUBLIC_KEY: process.env.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY,
};
